Traceback (most recent call last):
  File "C:\fork\Python_microcontroller_v1\Python\Reaction simulation system\main.py", line 223, in <module>
    main()
  File "C:\fork\Python_microcontroller_v1\Python\Reaction simulation system\main.py", line 180, in main
    response = read_controller_response(controller_response_file)
  File "C:\fork\Python_microcontroller_v1\Python\Reaction simulation system\main.py", line 53, in read_controller_response
    with open(filename, "r") as f:
  File "C:\Users\Len\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 260, in __init__
    def __init__(self, errors='strict'):
KeyboardInterrupt
er_v1\Python\Reaction simulation system\main.py", line 180, in main
    response = read_controller_response(controller_response_file)
  File "C:\fork\Python_microcontroller_v1\Python\Reaction simulation system\main.py", line 53, in read_controller_response
    Traceback (most recent call last):
  File "C:\fork\Python_microcontroller_v1\Python\System for loading data from the camera\main.py", line 10, in <module>
    cap = cv2.VideoCapture(0)
KeyboardInterrupt
eaction simulation system\main.py", line 180, in main
    response = read_controller_response(controller_response_file)
  File "C:\fork\Python_microcontroller_v1\Python\Reaction simulation system\main.py", line 53, in read_controller_response
    with open(filename, "r") as f:
  File "C:\Users\Len\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 260, in __init__
    def __init__(self, errors='strict'):
KeyboardInterrupt
on\Python310\lib\json\__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "C:\Users\Len\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 3, in <module>
    import re
  File "C:\Us    import re
  File "C:\Users\Len\AppData\Local\Programs\Python\Python310\lib\re.    import sre_compile
  File "C:\Users\Len\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 62, in <m  File "    _ignorecase_fixes = {i: tuple(j for j in t if i != j)
  File "C:\Users\Len\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 62, in <dictcomp>
    _ignorecase_fixes = {i: tuple(j for j in t if i != j)
KeyboardInterrupt
ootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
KeyboardInterrupt
en importlib._bootstrap_external>", line 147, in _path_stat
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\fork\Python_microcontroller_v1\Python\System for loading data from the camera\main.py", line 6, in <module>
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
KeyboardInterrupt

KeyboardInterrupt    import pygame.pkgdata
  File "C:\fork\Python_microcontroller_v1\Python\Smart Control Center\venv\lib\site-packages\pygame\pkgdata.py", line 25, in <module>
    from pkg_resources import resource_stream, resource_exists
  File "C:\fork\Python_microcontroller_v1\Python\Smart Control Center\venv\lib\site-packages\pkg_resources\__init__.py", line 23, in <module>
    import zipfile
  File "C:\Users\Len\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 19, in <module>
    import pathlib
  File "C:\Users\Len\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 410, in <module>
    class _TerminatingSelector:
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\fork\Python_microcontroller_v1\Python\System for loading data from the camera\main.py", line 63, in <module>
    print("No face detected")
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\fork\Python_microcontroller_v1\Python\System for loading data from the camera\main.py", line 63, in <module>
    print("No face detected")
OSError: [Errno 22] Invalid argument
Center\venv\lib\site-packages\pygame\__init__.py", line 337, in <module>
    print(
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\fork\Python_microcontroller_v1\Python\System for loading data from the camera\main.py", line 63, in <module>
    print("No face detected")
OSError: [Errno 22] Invalid argument
Center\venv\lib\site-packages\pygame\__init__.py", line 337, in <module>
    print(
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\fork\Python_microcontroller_v1\Python\System for loading data from the camera\main.py", line 110, in <module>
    print("Movement detected")
OSError: [Errno 22] Invalid argument
nter\venv\lib\site-packages\pygame\__init__.py", line 337, in <module>
    print(
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\fork\Python_microcontroller_v1\Python\System for loading data from the camera\main.py", line 110, in <module>
    print("Movement detected")
OSError: [Errno 22] Invalid argument
nter\venv\lib\site-packages\pygame\__init__.py", line 337, in <module>
    print(
OSError: [Errno 22] Invalid argument
